// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: calculator.proto
// Protobuf Java Version: 4.36.0

@com.google.protobuf.Generated
public final class CalculatorProto extends com.google.protobuf.GeneratedFile {
  private CalculatorProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 0,
      /* suffix= */ "",
      "CalculatorProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CalcRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CalcRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sequence = 1;</code>
     * @return The sequence.
     */
    int getSequence();

    /**
     * <code>double operand1 = 2;</code>
     * @return The operand1.
     */
    double getOperand1();

    /**
     * <code>string operator = 3;</code>
     * @return The operator.
     */
    java.lang.String getOperator();
    /**
     * <code>string operator = 3;</code>
     * @return The bytes for operator.
     */
    com.google.protobuf.ByteString
        getOperatorBytes();

    /**
     * <code>double operand2 = 4;</code>
     * @return The operand2.
     */
    double getOperand2();
  }
  /**
   * Protobuf type {@code CalcRequest}
   */
  public static final class CalcRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CalcRequest)
      CalcRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 0,
        /* suffix= */ "",
        "CalcRequest");
    }
    // Use CalcRequest.newBuilder() to construct.
    private CalcRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CalcRequest() {
      operator_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CalculatorProto.internal_static_CalcRequest_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return CalculatorProto.internal_static_CalcRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CalculatorProto.internal_static_CalcRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CalculatorProto.CalcRequest.class, CalculatorProto.CalcRequest.Builder.class);
    }

    public static final int SEQUENCE_FIELD_NUMBER = 1;
    private int sequence_ = 0;
    /**
     * <code>int32 sequence = 1;</code>
     * @return The sequence.
     */
    @java.lang.Override
    public int getSequence() {
      return sequence_;
    }

    public static final int OPERAND1_FIELD_NUMBER = 2;
    private double operand1_ = 0D;
    /**
     * <code>double operand1 = 2;</code>
     * @return The operand1.
     */
    @java.lang.Override
    public double getOperand1() {
      return operand1_;
    }

    public static final int OPERATOR_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object operator_ = "";
    /**
     * <code>string operator = 3;</code>
     * @return The operator.
     */
    @java.lang.Override
    public java.lang.String getOperator() {
      java.lang.Object ref = operator_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        operator_ = s;
        return s;
      }
    }
    /**
     * <code>string operator = 3;</code>
     * @return The bytes for operator.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOperatorBytes() {
      java.lang.Object ref = operator_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        operator_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERAND2_FIELD_NUMBER = 4;
    private double operand2_ = 0D;
    /**
     * <code>double operand2 = 4;</code>
     * @return The operand2.
     */
    @java.lang.Override
    public double getOperand2() {
      return operand2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sequence_ != 0) {
        output.writeInt32(1, sequence_);
      }
      if (java.lang.Double.doubleToRawLongBits(operand1_) != 0) {
        output.writeDouble(2, operand1_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(operator_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, operator_);
      }
      if (java.lang.Double.doubleToRawLongBits(operand2_) != 0) {
        output.writeDouble(4, operand2_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (sequence_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sequence_);
      }
      if (java.lang.Double.doubleToRawLongBits(operand1_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, operand1_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(operator_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, operator_);
      }
      if (java.lang.Double.doubleToRawLongBits(operand2_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, operand2_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CalculatorProto.CalcRequest)) {
        return super.equals(obj);
      }
      CalculatorProto.CalcRequest other = (CalculatorProto.CalcRequest) obj;

      if (getSequence()
          != other.getSequence()) return false;
      if (java.lang.Double.doubleToLongBits(getOperand1())
          != java.lang.Double.doubleToLongBits(
              other.getOperand1())) return false;
      if (!getOperator()
          .equals(other.getOperator())) return false;
      if (java.lang.Double.doubleToLongBits(getOperand2())
          != java.lang.Double.doubleToLongBits(
              other.getOperand2())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getSequence();
      hash = (37 * hash) + OPERAND1_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getOperand1()));
      hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
      hash = (53 * hash) + getOperator().hashCode();
      hash = (37 * hash) + OPERAND2_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getOperand2()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CalculatorProto.CalcRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CalculatorProto.CalcRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CalculatorProto.CalcRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CalculatorProto.CalcRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CalculatorProto.CalcRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CalculatorProto.CalcRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CalculatorProto.CalcRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CalculatorProto.CalcRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static CalculatorProto.CalcRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static CalculatorProto.CalcRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CalculatorProto.CalcRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CalculatorProto.CalcRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CalculatorProto.CalcRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CalcRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CalcRequest)
        CalculatorProto.CalcRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CalculatorProto.internal_static_CalcRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CalculatorProto.internal_static_CalcRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CalculatorProto.CalcRequest.class, CalculatorProto.CalcRequest.Builder.class);
      }

      // Construct using CalculatorProto.CalcRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sequence_ = 0;
        operand1_ = 0D;
        operator_ = "";
        operand2_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CalculatorProto.internal_static_CalcRequest_descriptor;
      }

      @java.lang.Override
      public CalculatorProto.CalcRequest getDefaultInstanceForType() {
        return CalculatorProto.CalcRequest.getDefaultInstance();
      }

      @java.lang.Override
      public CalculatorProto.CalcRequest build() {
        CalculatorProto.CalcRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CalculatorProto.CalcRequest buildPartial() {
        CalculatorProto.CalcRequest result = new CalculatorProto.CalcRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(CalculatorProto.CalcRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sequence_ = sequence_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.operand1_ = operand1_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.operator_ = operator_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.operand2_ = operand2_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CalculatorProto.CalcRequest) {
          return mergeFrom((CalculatorProto.CalcRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CalculatorProto.CalcRequest other) {
        if (other == CalculatorProto.CalcRequest.getDefaultInstance()) return this;
        if (other.getSequence() != 0) {
          setSequence(other.getSequence());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getOperand1()) != 0) {
          setOperand1(other.getOperand1());
        }
        if (!other.getOperator().isEmpty()) {
          operator_ = other.operator_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (java.lang.Double.doubleToRawLongBits(other.getOperand2()) != 0) {
          setOperand2(other.getOperand2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        java.util.Objects.requireNonNull(extensionRegistry);
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                sequence_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 17: {
                operand1_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 26: {
                operator_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 33: {
                operand2_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int sequence_ ;
      /**
       * <code>int32 sequence = 1;</code>
       * @return The sequence.
       */
      @java.lang.Override
      public int getSequence() {
        return sequence_;
      }
      /**
       * <code>int32 sequence = 1;</code>
       * @param value The sequence to set.
       * @return This builder for chaining.
       */
      public Builder setSequence(int value) {

        sequence_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sequence = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequence() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sequence_ = 0;
        onChanged();
        return this;
      }

      private double operand1_ ;
      /**
       * <code>double operand1 = 2;</code>
       * @return The operand1.
       */
      @java.lang.Override
      public double getOperand1() {
        return operand1_;
      }
      /**
       * <code>double operand1 = 2;</code>
       * @param value The operand1 to set.
       * @return This builder for chaining.
       */
      public Builder setOperand1(double value) {

        operand1_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double operand1 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperand1() {
        bitField0_ = (bitField0_ & ~0x00000002);
        operand1_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object operator_ = "";
      /**
       * <code>string operator = 3;</code>
       * @return The operator.
       */
      public java.lang.String getOperator() {
        java.lang.Object ref = operator_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          operator_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string operator = 3;</code>
       * @return The bytes for operator.
       */
      public com.google.protobuf.ByteString
          getOperatorBytes() {
        java.lang.Object ref = operator_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          operator_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string operator = 3;</code>
       * @param value The operator to set.
       * @return This builder for chaining.
       */
      public Builder setOperator(
          java.lang.String value) {
        java.util.Objects.requireNonNull(value);
        operator_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string operator = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperator() {
        operator_ = getDefaultInstance().getOperator();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string operator = 3;</code>
       * @param value The bytes for operator to set.
       * @return This builder for chaining.
       */
      public Builder setOperatorBytes(
          com.google.protobuf.ByteString value) {
        java.util.Objects.requireNonNull(value);
        checkByteStringIsUtf8(value);
        operator_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private double operand2_ ;
      /**
       * <code>double operand2 = 4;</code>
       * @return The operand2.
       */
      @java.lang.Override
      public double getOperand2() {
        return operand2_;
      }
      /**
       * <code>double operand2 = 4;</code>
       * @param value The operand2 to set.
       * @return This builder for chaining.
       */
      public Builder setOperand2(double value) {

        operand2_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double operand2 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperand2() {
        bitField0_ = (bitField0_ & ~0x00000008);
        operand2_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CalcRequest)
    }

    // @@protoc_insertion_point(class_scope:CalcRequest)
    private static final CalculatorProto.CalcRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CalculatorProto.CalcRequest();
    }

    public static CalculatorProto.CalcRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CalcRequest>
        PARSER = new com.google.protobuf.AbstractParser<CalcRequest>() {
      @java.lang.Override
      public CalcRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CalcRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CalcRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CalculatorProto.CalcRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CalcResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CalcResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sequence = 1;</code>
     * @return The sequence.
     */
    int getSequence();

    /**
     * <code>bool success = 2;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>double result = 3;</code>
     * @return The result.
     */
    double getResult();

    /**
     * <code>string error_message = 4;</code>
     * @return The errorMessage.
     */
    java.lang.String getErrorMessage();
    /**
     * <code>string error_message = 4;</code>
     * @return The bytes for errorMessage.
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();
  }
  /**
   * Protobuf type {@code CalcResponse}
   */
  public static final class CalcResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CalcResponse)
      CalcResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 0,
        /* suffix= */ "",
        "CalcResponse");
    }
    // Use CalcResponse.newBuilder() to construct.
    private CalcResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CalcResponse() {
      errorMessage_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CalculatorProto.internal_static_CalcResponse_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return CalculatorProto.internal_static_CalcResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CalculatorProto.internal_static_CalcResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CalculatorProto.CalcResponse.class, CalculatorProto.CalcResponse.Builder.class);
    }

    public static final int SEQUENCE_FIELD_NUMBER = 1;
    private int sequence_ = 0;
    /**
     * <code>int32 sequence = 1;</code>
     * @return The sequence.
     */
    @java.lang.Override
    public int getSequence() {
      return sequence_;
    }

    public static final int SUCCESS_FIELD_NUMBER = 2;
    private boolean success_ = false;
    /**
     * <code>bool success = 2;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int RESULT_FIELD_NUMBER = 3;
    private double result_ = 0D;
    /**
     * <code>double result = 3;</code>
     * @return The result.
     */
    @java.lang.Override
    public double getResult() {
      return result_;
    }

    public static final int ERROR_MESSAGE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object errorMessage_ = "";
    /**
     * <code>string error_message = 4;</code>
     * @return The errorMessage.
     */
    @java.lang.Override
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string error_message = 4;</code>
     * @return The bytes for errorMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sequence_ != 0) {
        output.writeInt32(1, sequence_);
      }
      if (success_ != false) {
        output.writeBool(2, success_);
      }
      if (java.lang.Double.doubleToRawLongBits(result_) != 0) {
        output.writeDouble(3, result_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, errorMessage_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (sequence_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sequence_);
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, success_);
      }
      if (java.lang.Double.doubleToRawLongBits(result_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, result_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(errorMessage_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, errorMessage_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CalculatorProto.CalcResponse)) {
        return super.equals(obj);
      }
      CalculatorProto.CalcResponse other = (CalculatorProto.CalcResponse) obj;

      if (getSequence()
          != other.getSequence()) return false;
      if (getSuccess()
          != other.getSuccess()) return false;
      if (java.lang.Double.doubleToLongBits(getResult())
          != java.lang.Double.doubleToLongBits(
              other.getResult())) return false;
      if (!getErrorMessage()
          .equals(other.getErrorMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getSequence();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getResult()));
      hash = (37 * hash) + ERROR_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getErrorMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CalculatorProto.CalcResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CalculatorProto.CalcResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CalculatorProto.CalcResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CalculatorProto.CalcResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CalculatorProto.CalcResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CalculatorProto.CalcResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CalculatorProto.CalcResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CalculatorProto.CalcResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static CalculatorProto.CalcResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static CalculatorProto.CalcResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CalculatorProto.CalcResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static CalculatorProto.CalcResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CalculatorProto.CalcResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CalcResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CalcResponse)
        CalculatorProto.CalcResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CalculatorProto.internal_static_CalcResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CalculatorProto.internal_static_CalcResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CalculatorProto.CalcResponse.class, CalculatorProto.CalcResponse.Builder.class);
      }

      // Construct using CalculatorProto.CalcResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        sequence_ = 0;
        success_ = false;
        result_ = 0D;
        errorMessage_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CalculatorProto.internal_static_CalcResponse_descriptor;
      }

      @java.lang.Override
      public CalculatorProto.CalcResponse getDefaultInstanceForType() {
        return CalculatorProto.CalcResponse.getDefaultInstance();
      }

      @java.lang.Override
      public CalculatorProto.CalcResponse build() {
        CalculatorProto.CalcResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public CalculatorProto.CalcResponse buildPartial() {
        CalculatorProto.CalcResponse result = new CalculatorProto.CalcResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(CalculatorProto.CalcResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.sequence_ = sequence_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.success_ = success_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.result_ = result_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.errorMessage_ = errorMessage_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CalculatorProto.CalcResponse) {
          return mergeFrom((CalculatorProto.CalcResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CalculatorProto.CalcResponse other) {
        if (other == CalculatorProto.CalcResponse.getDefaultInstance()) return this;
        if (other.getSequence() != 0) {
          setSequence(other.getSequence());
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (java.lang.Double.doubleToRawLongBits(other.getResult()) != 0) {
          setResult(other.getResult());
        }
        if (!other.getErrorMessage().isEmpty()) {
          errorMessage_ = other.errorMessage_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        java.util.Objects.requireNonNull(extensionRegistry);
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                sequence_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                success_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 25: {
                result_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 34: {
                errorMessage_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int sequence_ ;
      /**
       * <code>int32 sequence = 1;</code>
       * @return The sequence.
       */
      @java.lang.Override
      public int getSequence() {
        return sequence_;
      }
      /**
       * <code>int32 sequence = 1;</code>
       * @param value The sequence to set.
       * @return This builder for chaining.
       */
      public Builder setSequence(int value) {

        sequence_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sequence = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSequence() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sequence_ = 0;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 2;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 2;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {

        success_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        bitField0_ = (bitField0_ & ~0x00000002);
        success_ = false;
        onChanged();
        return this;
      }

      private double result_ ;
      /**
       * <code>double result = 3;</code>
       * @return The result.
       */
      @java.lang.Override
      public double getResult() {
        return result_;
      }
      /**
       * <code>double result = 3;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(double value) {

        result_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double result = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000004);
        result_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object errorMessage_ = "";
      /**
       * <code>string error_message = 4;</code>
       * @return The errorMessage.
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string error_message = 4;</code>
       * @return The bytes for errorMessage.
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string error_message = 4;</code>
       * @param value The errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        java.util.Objects.requireNonNull(value);
        errorMessage_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string error_message = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorMessage() {
        errorMessage_ = getDefaultInstance().getErrorMessage();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string error_message = 4;</code>
       * @param value The bytes for errorMessage to set.
       * @return This builder for chaining.
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        java.util.Objects.requireNonNull(value);
        checkByteStringIsUtf8(value);
        errorMessage_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CalcResponse)
    }

    // @@protoc_insertion_point(class_scope:CalcResponse)
    private static final CalculatorProto.CalcResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CalculatorProto.CalcResponse();
    }

    public static CalculatorProto.CalcResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CalcResponse>
        PARSER = new com.google.protobuf.AbstractParser<CalcResponse>() {
      @java.lang.Override
      public CalcResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CalcResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CalcResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public CalculatorProto.CalcResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalcRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CalcRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CalcResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CalcResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020calculator.proto\"U\n\013CalcRequest\022\020\n\010seq" +
      "uence\030\001 \001(\005\022\020\n\010operand1\030\002 \001(\001\022\020\n\010operato" +
      "r\030\003 \001(\t\022\020\n\010operand2\030\004 \001(\001\"X\n\014CalcRespons" +
      "e\022\020\n\010sequence\030\001 \001(\005\022\017\n\007success\030\002 \001(\010\022\016\n\006" +
      "result\030\003 \001(\001\022\025\n\rerror_message\030\004 \001(\tB\021B\017C" +
      "alculatorProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_CalcRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_CalcRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CalcRequest_descriptor,
        new java.lang.String[] { "Sequence", "Operand1", "Operator", "Operand2", });
    internal_static_CalcResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_CalcResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CalcResponse_descriptor,
        new java.lang.String[] { "Sequence", "Success", "Result", "ErrorMessage", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
